/**
 * iso-countries.ts — ISO 3166-1 alpha-2 codes with Serbian display names.
 *
 * The primary use is the checkout "Firma — inostranstvo" country
 * select. The `code` is what we persist on Order.companyCountryCode
 * (it ends up on the invoice). The `label` is the customer-facing
 * Serbian name.
 *
 * Top of the list carries common regional + Balkan markets so the
 * 90% case is one click instead of a scroll. The rest follows
 * Serbian-locale alphabetical order.
 *
 * Names follow ISO 3166 geopolitical naming where possible. Where
 * there's an established Serbian short form (Nemačka, Češka), we use
 * it. RS is intentionally absent from the foreign-company list — that
 * branch of checkout is for company_foreign only.
 */

export type IsoCountry = {
  code: string;
  label: string;
};

const POPULAR: IsoCountry[] = [
  { code: "DE", label: "Nemačka" },
  { code: "AT", label: "Austrija" },
  { code: "CH", label: "Švajcarska" },
  { code: "IT", label: "Italija" },
  { code: "FR", label: "Francuska" },
  { code: "GB", label: "Velika Britanija" },
  { code: "NL", label: "Holandija" },
  { code: "BE", label: "Belgija" },
  { code: "ES", label: "Španija" },
  { code: "HR", label: "Hrvatska" },
  { code: "SI", label: "Slovenija" },
  { code: "BA", label: "Bosna i Hercegovina" },
  { code: "ME", label: "Crna Gora" },
  { code: "MK", label: "Severna Makedonija" },
  { code: "HU", label: "Mađarska" },
  { code: "US", label: "Sjedinjene Američke Države" },
];

const REST: IsoCountry[] = [
  { code: "AF", label: "Avganistan" },
  { code: "AL", label: "Albanija" },
  { code: "DZ", label: "Alžir" },
  { code: "AD", label: "Andora" },
  { code: "AO", label: "Angola" },
  { code: "AG", label: "Antigva i Barbuda" },
  { code: "AR", label: "Argentina" },
  { code: "AM", label: "Jermenija" },
  { code: "AU", label: "Australija" },
  { code: "AZ", label: "Azerbejdžan" },
  { code: "BS", label: "Bahami" },
  { code: "BH", label: "Bahrein" },
  { code: "BD", label: "Bangladeš" },
  { code: "BB", label: "Barbados" },
  { code: "BY", label: "Belorusija" },
  { code: "BZ", label: "Belize" },
  { code: "BJ", label: "Benin" },
  { code: "BT", label: "Butan" },
  { code: "BO", label: "Bolivija" },
  { code: "BW", label: "Bocvana" },
  { code: "BR", label: "Brazil" },
  { code: "BN", label: "Brunej" },
  { code: "BG", label: "Bugarska" },
  { code: "BF", label: "Burkina Faso" },
  { code: "BI", label: "Burundi" },
  { code: "CV", label: "Zelenortska Republika" },
  { code: "KH", label: "Kambodža" },
  { code: "CM", label: "Kamerun" },
  { code: "CA", label: "Kanada" },
  { code: "CF", label: "Centralnoafrička Republika" },
  { code: "TD", label: "Čad" },
  { code: "CL", label: "Čile" },
  { code: "CN", label: "Kina" },
  { code: "CO", label: "Kolumbija" },
  { code: "KM", label: "Komori" },
  { code: "CG", label: "Kongo" },
  { code: "CD", label: "Demokratska Republika Kongo" },
  { code: "CR", label: "Kostarika" },
  { code: "CI", label: "Obala Slonovače" },
  { code: "CU", label: "Kuba" },
  { code: "CY", label: "Kipar" },
  { code: "CZ", label: "Češka" },
  { code: "DK", label: "Danska" },
  { code: "DJ", label: "Džibuti" },
  { code: "DM", label: "Dominika" },
  { code: "DO", label: "Dominikanska Republika" },
  { code: "EC", label: "Ekvador" },
  { code: "EG", label: "Egipat" },
  { code: "SV", label: "Salvador" },
  { code: "GQ", label: "Ekvatorijalna Gvineja" },
  { code: "ER", label: "Eritreja" },
  { code: "EE", label: "Estonija" },
  { code: "SZ", label: "Esvatini" },
  { code: "ET", label: "Etiopija" },
  { code: "FJ", label: "Fidži" },
  { code: "FI", label: "Finska" },
  { code: "GA", label: "Gabon" },
  { code: "GM", label: "Gambija" },
  { code: "GE", label: "Gruzija" },
  { code: "GH", label: "Gana" },
  { code: "GR", label: "Grčka" },
  { code: "GD", label: "Grenada" },
  { code: "GT", label: "Gvatemala" },
  { code: "GN", label: "Gvineja" },
  { code: "GW", label: "Gvineja Bisao" },
  { code: "GY", label: "Gvajana" },
  { code: "HT", label: "Haiti" },
  { code: "HN", label: "Honduras" },
  { code: "HK", label: "Hong Kong" },
  { code: "IS", label: "Island" },
  { code: "IN", label: "Indija" },
  { code: "ID", label: "Indonezija" },
  { code: "IR", label: "Iran" },
  { code: "IQ", label: "Irak" },
  { code: "IE", label: "Irska" },
  { code: "IL", label: "Izrael" },
  { code: "JM", label: "Jamajka" },
  { code: "JP", label: "Japan" },
  { code: "JO", label: "Jordan" },
  { code: "KZ", label: "Kazahstan" },
  { code: "KE", label: "Kenija" },
  { code: "KI", label: "Kiribati" },
  { code: "KP", label: "Severna Koreja" },
  { code: "KR", label: "Južna Koreja" },
  { code: "KW", label: "Kuvajt" },
  { code: "KG", label: "Kirgistan" },
  { code: "LA", label: "Laos" },
  { code: "LV", label: "Letonija" },
  { code: "LB", label: "Liban" },
  { code: "LS", label: "Lesoto" },
  { code: "LR", label: "Liberija" },
  { code: "LY", label: "Libija" },
  { code: "LI", label: "Lihtenštajn" },
  { code: "LT", label: "Litvanija" },
  { code: "LU", label: "Luksemburg" },
  { code: "MO", label: "Makao" },
  { code: "MG", label: "Madagaskar" },
  { code: "MW", label: "Malavi" },
  { code: "MY", label: "Malezija" },
  { code: "MV", label: "Maldivi" },
  { code: "ML", label: "Mali" },
  { code: "MT", label: "Malta" },
  { code: "MH", label: "Maršalska Ostrva" },
  { code: "MR", label: "Mauritanija" },
  { code: "MU", label: "Mauricijus" },
  { code: "MX", label: "Meksiko" },
  { code: "FM", label: "Mikronezija" },
  { code: "MD", label: "Moldavija" },
  { code: "MC", label: "Monako" },
  { code: "MN", label: "Mongolija" },
  { code: "MA", label: "Maroko" },
  { code: "MZ", label: "Mozambik" },
  { code: "MM", label: "Mjanmar" },
  { code: "NA", label: "Namibija" },
  { code: "NR", label: "Nauru" },
  { code: "NP", label: "Nepal" },
  { code: "NZ", label: "Novi Zeland" },
  { code: "NI", label: "Nikaragva" },
  { code: "NE", label: "Niger" },
  { code: "NG", label: "Nigerija" },
  { code: "NO", label: "Norveška" },
  { code: "OM", label: "Oman" },
  { code: "PK", label: "Pakistan" },
  { code: "PW", label: "Palau" },
  { code: "PA", label: "Panama" },
  { code: "PG", label: "Papua Nova Gvineja" },
  { code: "PY", label: "Paragvaj" },
  { code: "PE", label: "Peru" },
  { code: "PH", label: "Filipini" },
  { code: "PL", label: "Poljska" },
  { code: "PT", label: "Portugal" },
  { code: "QA", label: "Katar" },
  { code: "RO", label: "Rumunija" },
  { code: "RU", label: "Rusija" },
  { code: "RW", label: "Ruanda" },
  { code: "KN", label: "Sveti Kristofor i Nevis" },
  { code: "LC", label: "Sveta Lucija" },
  { code: "VC", label: "Sveti Vinsent i Grenadini" },
  { code: "WS", label: "Samoa" },
  { code: "SM", label: "San Marino" },
  { code: "ST", label: "Sao Tome i Principe" },
  { code: "SA", label: "Saudijska Arabija" },
  { code: "SN", label: "Senegal" },
  { code: "SC", label: "Sejšeli" },
  { code: "SL", label: "Sijera Leone" },
  { code: "SG", label: "Singapur" },
  { code: "SK", label: "Slovačka" },
  { code: "SB", label: "Solomonska Ostrva" },
  { code: "SO", label: "Somalija" },
  { code: "ZA", label: "Južnoafrička Republika" },
  { code: "SS", label: "Južni Sudan" },
  { code: "LK", label: "Šri Lanka" },
  { code: "SD", label: "Sudan" },
  { code: "SR", label: "Surinam" },
  { code: "SE", label: "Švedska" },
  { code: "SY", label: "Sirija" },
  { code: "TW", label: "Tajvan" },
  { code: "TJ", label: "Tadžikistan" },
  { code: "TZ", label: "Tanzanija" },
  { code: "TH", label: "Tajland" },
  { code: "TL", label: "Istočni Timor" },
  { code: "TG", label: "Togo" },
  { code: "TO", label: "Tonga" },
  { code: "TT", label: "Trinidad i Tobago" },
  { code: "TN", label: "Tunis" },
  { code: "TR", label: "Turska" },
  { code: "TM", label: "Turkmenistan" },
  { code: "TV", label: "Tuvalu" },
  { code: "UG", label: "Uganda" },
  { code: "UA", label: "Ukrajina" },
  { code: "AE", label: "Ujedinjeni Arapski Emirati" },
  { code: "UY", label: "Urugvaj" },
  { code: "UZ", label: "Uzbekistan" },
  { code: "VU", label: "Vanuatu" },
  { code: "VA", label: "Vatikan" },
  { code: "VE", label: "Venecuela" },
  { code: "VN", label: "Vijetnam" },
  { code: "YE", label: "Jemen" },
  { code: "ZM", label: "Zambija" },
  { code: "ZW", label: "Zimbabve" },
];

const collator = new Intl.Collator("sr-Latn-RS");
REST.sort((a, b) => collator.compare(a.label, b.label));

/**
 * Single ordered list with a sentinel separator. The select component
 * renders the popular block, a `disabled` divider option, then the
 * alphabetical rest. Consumers that just want the list (e.g.
 * validation lookups) can filter out the separator on `code !== ""`.
 */
export const COUNTRIES: IsoCountry[] = [
  ...POPULAR,
  { code: "", label: "──────────" },
  ...REST,
];

export function getCountryLabel(code: string): string | null {
  const upper = code.toUpperCase();
  const hit = COUNTRIES.find((c) => c.code === upper);
  return hit?.label ?? null;
}
